_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1
auto_select_gpus: True

log_every_n_steps: 1
max_epochs: 10

enable_model_summary: False
enable_progress_bar: False