_target_: src.strand.STRAND

# Training
data_dir:
  X: ${work_dir}/data/${data_name}/feature.pkl
  Y: ${work_dir}/data/${data_name}/snv.pkl

rank: 5
t_dim: 2
r_dim: 2
e_dim: 16
n_dim: 4
c_dim: 2

use_covariate: True

# Initialization
init: NMF
nmf_max_iter: 100000

# E step
e_iter: 10
laplace_approx_conf:
  lr: 0.01
  max_iter: 1000
  batch_size: 512

# M step
tf_lr: 0.1
tf_batch_size: 64
tf_max_steps: 500

bias_correction: False
uniform_missing_rate: True