model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "negative_elbo"
  save_top_k: -1
  save_last: True
  mode: "min"
  dirpath: "checkpoints/"
  filename: "sample-{epoch:02d}"
  save_weights_only: True

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "negative_elbo"
  mode: "min"
  patience: 1
  min_delta: 0.1