model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "negative_elbo_epoch"
  save_top_k: 1
  save_last: False
  mode: "min"
  dirpath: "checkpoints/"
  filename: "sample-{epoch:02d}"
  save_weights_only: True

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "negative_elbo_epoch"
  patience: 15
  mode: "min"
  verbose: True
  check_finite: True
