# @package _global_

# specify here default training configuration
defaults:
  - trainer: default.yaml
  - model: default.yaml
  - datamodule: default.yaml
  - experiment: null

  - hydra: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/

callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "negative_elbo_epoch"
    save_top_k: 1
    save_last: False
    mode: "min"
    dirpath: "checkpoints/"
    filename: "sample-{epoch:02d}"
    save_weights_only: True
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "negative_elbo_epoch"
    patience: 5
    mode: "min"


logger:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "STRAND-Lightning"
  save_dir: "."
  group: ${data_name}
  name: ${data_name}_rank_${model.rank}
  tags: [
      "rank:${model.rank}",
      "data:${data_name}",
      "use_covariate:${model.use_covariate}",
      "bias_correction:${model.bias_correction}",
      "uniform_missing_rate:${model.uniform_missing_rate}"
  ]

debug: False
print_config: True
ignore_warnings: True

test_after_training: True